Import turtle

#body
turtle.showturtle() 
turtle.shape("turtle") 
turtle.pencolor("brown")
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(30)
turtle.forward(100)
turtle.right(120)
turtle.forward(100)
turtle.right(30)
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.penup()
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(110)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.pendown()
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(20)
turtle.penup()
turtle.backward(10)
turtle.right(90)
turtle.forward(18)
turtle.pendown()
turtle.circle(1)
turtle.penup()
turtle.home()
input()



